baseURL = '/'
title = 'Heritage Carvers Hub'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true #consistent URL structure for all languages
enableInlineShortcodes = true
disableFastRender = false #Fast render is enabled [Hugo rebuilds only changed pages]
relativeURLs = true #Makes links relative [Best for Local or portable hosting]
#canonifyURLs = true #Makes links absolute using baseURL [Production & SEO]

[languages]
  [languages.en]
    languageName = "EN"
    languageCode = "en"
    weight = 1
    contentDir = "content/en"

  [languages.ne]
    languageName = "NE"
    weight = 2
    contentDir = "content/ne"

  [languages.jp]
    languageName = "JP"
    languageCode = "ja"
    weight = 3
    contentDir = "content/jp"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true #Allow raw HTML inside Markdown files.
